export enum QuestionType {
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  YES_NO = 'YES_NO',
  SCALE_1_5 = 'SCALE_1_5',
  RATING_1_5 = 'RATING_1_5',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  FREQUENCY = 'FREQUENCY',
}
